### PR TITLE
Simplified completions - Always to stdout

### PR DESCRIPTION
**Pull request by codepope**
Simplified completions - made it -c or --completion - always outputs to stdout.

### CODE REVIEW

**Comment by michaeldwan** [comment]
@codepope how about we make this a new `completions` command?

**Comment by codepope** [comment]
I'm very aware of the limited namespace we have to play with with commands @michaeldwan - completions is already in the c-space with certs and config.

flyctl util completions maybe?

**Comment by michaeldwan** [comment]
Good point! How do you feel about merging this to fix your issue and improve later?

**Comment by codepope** [comment]
I feel good... </james brown>

**Pull request merged**
