### PR TITLE
fix: Update wording highlight force flag overrides state

### PR DESCRIPTION
**Pull request by shortdiv**
Screen Shot 2023-03-07 at 11 45 14 AM

### CODE REVIEW

**Comment by matttpt** [comment]
As part of this, maybe it's worth it to update [this](https://github.com/superfly/flyctl/blob/d5c82a3f871681f269c685d571924b3ad6b4a57c/internal/command/machine/destroy.go#L88) `switch` to write a message for all non-stopped states?

**Comment by shortdiv** [comment]
Great idea @matttpt, I've updated this with a catch all so the messaging is clearer

**Review by tvdfly — APPROVED** [review]
thanks!

**Comment by dangra** [comment]
@shortdiv all it needs is a rebase to pass pre-commit checks

**Comment by shortdiv** [comment]
Rebased!

**Review by dangra — APPROVED** [review]

**Pull request merged**
