### PR TITLE
Update Nuxt scanner and Dockerfile

### PR DESCRIPTION
**Pull request by redjonzaci**
### Change Summary

Related to: #2658

### CODE REVIEW

**Comment by Rohithgilla12** [comment]
Do we have any update when it might be merged 🙈

**Comment by dangra** [comment]
will be shipped in v0.1.114, please @Rohithgilla12 test it and confirm it works as expected

**Comment by Rohithgilla12** [comment]
@dangra Looks like it doesn't work :( 


Created a new `nuxt` project with `pnpm dlx nuxi@latest init fly-test`


`fly` version
image

`fly launch`
image

**Comment by dangra** [comment]
The problem here seems to be that the [scanner's priority order for Nuxt](https://github.com/superfly/flyctl/blob/93001806ee467ed760df247337b31fa0d585d5b6/scanner/scanner.go#L119) is way below the generic [JsFramework](https://github.com/superfly/flyctl/blob/93001806ee467ed760df247337b31fa0d585d5b6/scanner/scanner.go#L108) scanner, so the project is detected as a "NodeJS" app.

@rubys my understanding of Javascript frameworks is very limited, no idea what is the best approach here, either add Nuxt support to JsFramework scanner or move Nuxt scanner up in the chain. What do you suggest?

**Comment by Rohithgilla12** [comment]
@dangra I would suggest moving up the chain since they have a very particular config files per framework.
`Nuxt` -> `nuxt.config.ts`
`Next` -> `next.config.ts`
`Remix` -> `remix.config.js`

**Comment by rubys** [comment]
Sorry, just noticing this now.  I would prefer to update the JSFramework scanner.

Basically the previous scanners would drop a precanned Dockerfile into your directory and you are on your own.  The current nuxt file assumes yarn, but perhaps you are using npm or pnpm or bun?  Perhaps you want caching?  Perhaps you are on Windows?  Perhaps you use puppeteer?  legacy-peer-deps?  sqlite3?  litefs?

**Pull request merged**
