### PR TITLE
Meteor 3 scanner

### PR DESCRIPTION
**Pull request by kylemclaren**
### Change Summary

What and Why: A scanner for [Meteor](https://meteor.com) apps. Much anticipated Meteor 3 launch is coming in the next week or two. This is a (formerly) huge community so it would be good to cater to these apps in the scanner.

Related:

- https://github.com/fly-apps/dockerfile-node/pull/92

### Test

```console
git clone github.com/fly-apps/meteor-3-demo
rm Dockerfile fly.toml
```

```console
git clone github.com/superfly/flyctl
cd flyctl
git checkout feat/meteor-scanner
make build
```

```console
cd meteor-3-demo
/path/to/built/flyctl launch
```

---

### Documentation

- [ ] Fresh Produce
- [ ] In superfly/docs, or asked for help from docs team
- [ ] n/a

### CODE REVIEW

**Comment by kylemclaren** [comment]
A bit stuck here. It _appears_ Meteor app is detected, but it doesn't use the correct Dockerfile template and instead runs `@flydotio/dockerfile@latest`

```console
➜ ../bin/flyctl launch --no-deploy  --name meteor-test-flyctl
Scanning source code
Detected a Meteor app
Creating app in ...
We're about to launch your Meteor app on Fly.io. Here's what you're getting:

...

? Do you want to tweak these settings before proceeding? No
Created app 'meteor-test-flyctl-4' in organization 'personal'
Admin URL: https://fly.io/apps/meteor-test-flyctl
Hostname: meteor-test-flyctl.fly.dev

...

installing: npx --yes @flydotio/dockerfile@latest
     create  Dockerfile
Wrote config file fly.toml
Validating /Users/kyle/Git/superfly/flyctl/meteor3/fly.toml
✓ Configuration is valid

If you need custom packages installed, or have problems with your deployment
build, you may need to edit the Dockerfile for app-specific changes. If you
need help, please post on https://community.fly.io.

Now: run 'fly deploy' to deploy your Node.js app.
```

**Comment by kylemclaren** [comment]
A bit stuck here. It _appears_ Meteor app is detected, but it doesn't use the correct Dockerfile template and instead runs `@flydotio/dockerfile@latest`

```console
➜ ../bin/flyctl launch --no-deploy  --name meteor-test-flyctl
Scanning source code
Detected a Meteor app
Creating app in ...
We're about to launch your Meteor app on Fly.io. Here's what you're getting:

...

? Do you want to tweak these settings before proceeding? No
Created app 'meteor-test-flyctl-4' in organization 'personal'
Admin URL: https://fly.io/apps/meteor-test-flyctl
Hostname: meteor-test-flyctl.fly.dev

...

installing: npx --yes @flydotio/dockerfile@latest
     create  Dockerfile
Wrote config file fly.toml
...
✓ Configuration is valid

If you need custom packages installed, or have problems with your deployment
build, you may need to edit the Dockerfile for app-specific changes. If you
need help, please post on https://community.fly.io.

Now: run 'fly deploy' to deploy your Node.js app.
```

**Comment by kylemclaren** [comment]
A bit stuck here. It _appears_ Meteor app is detected, but it doesn't use the correct Dockerfile template and instead runs `@flydotio/dockerfile@latest`

```console
➜ ../bin/flyctl launch --no-deploy  --name meteor-test-flyctl
Scanning source code
Detected a Meteor app
Creating app in ...
We're about to launch your Meteor app on Fly.io. Here's what you're getting:

...

? Do you want to tweak these settings before proceeding? No
Created app 'meteor-test-flyctl' in organization 'personal'
Admin URL: https://fly.io/apps/meteor-test-flyctl
Hostname: meteor-test-flyctl.fly.dev

...

installing: npx --yes @flydotio/dockerfile@latest
     create  Dockerfile
Wrote config file fly.toml
...
✓ Configuration is valid

If you need custom packages installed, or have problems with your deployment
build, you may need to edit the Dockerfile for app-specific changes. If you
need help, please post on https://community.fly.io.

Now: run 'fly deploy' to deploy your Node.js app.
```

**Comment by kylemclaren** [comment]
A bit stuck here. It _appears_ Meteor app is detected, but it doesn't use the correct Dockerfile template and instead runs `@flydotio/dockerfile@latest`

```console
➜ ../bin/flyctl launch --no-deploy  --name meteor-test-flyctl
Scanning source code
Detected a Meteor app
Creating app in ...
We're about to launch your Meteor app on Fly.io. Here's what you're getting:

...

? Do you want to tweak these settings before proceeding? No
Created app 'meteor-test-flyctl' in organization 'personal'
Admin URL: https://fly.io/apps/meteor-test-flyctl
Hostname: meteor-test-flyctl.fly.dev

...

installing: npx --yes @flydotio/dockerfile@latest
     create  Dockerfile
Wrote config file fly.toml
...
✓ Configuration is valid

If you need custom packages installed, or have problems with your deployment
build, you may need to edit the Dockerfile for app-specific changes. If you
need help, please post on https://community.fly.io.

Now: run 'fly deploy' to deploy your Node.js app.
```

**Review by rubys — APPROVED** [review]

**Pull request merged**
