### PR TITLE
allow specifying builder scope for a single app or an org

### PR DESCRIPTION
**Pull request by billyb2**
### Change Summary

What and Why:
you can now specify --depot-scope=app to make sure your app's builder cache isn't shared by other apps

How:
Just added another field to the mutation. most of the 'work' is in web

Related to:

---

### Documentation

- [x] Fresh Produce
- [ ] In superfly/docs, or asked for help from docs team
- [ ] n/a

### CODE REVIEW

**Comment by billyb2** [comment]
waiting until https://github.com/superfly/web/pull/3369 is merged, and i need https://github.com/superfly/fly-go/pull/96 merged too

**Comment by jtarchie** [comment]
This appears to have broken my ability to run this command:

```bash
$ fly machine run . --name "assign_1724281420" --volume "vol_vzkmojjmznl1wwev:/var/osm" --region sjc --rm --debug --verbose
Error: invalid depot-scope value. must be 'org' or 'app'
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x64
github.com/superfly/flyctl/internal/cli.printError(0x1400099c000, 0x1400062fc06, 0x140009cb208, {0x1065af608, 0x14000062a10})
        github.com/superfly/flyctl/internal/cli/cli.go:184 +0x450
github.com/superfly/flyctl/internal/cli.Run({0x1065d1150?, 0x1400066ee00?}, 0x1400099c000, {0x14000146690, 0xc, 0xc})
        github.com/superfly/flyctl/internal/cli/cli.go:117 +0x870
main.run()
        github.com/superfly/flyctl/main.go:47 +0x174
main.main()
        github.com/superfly/flyctl/main.go:26 +0x20
```

The version of the CLI I am using:

```
fly v0.2.118 darwin/arm64 Commit: a7a30da947c4ce0675a0cb678f5bc684f2f8d0d6 BuildDate: 2024-08-21T20:25:58Z
```

**Comment by billyb2** [comment]
yep you're right, that appears to be the case. i'm fixing this now. thank you for the catch

**Comment by billyb2** [comment]
alright, the upcoming v0.2.119 should have a fix merged in

**Comment by jtarchie** [comment]
Great!

How long before `fly version upgrade` picks up the changes?

**Comment by jtarchie** [comment]
I think things might just be cached for me. I've installed via homebrew, and the [JSON](https://formulae.brew.sh/api/formula/flyctl.json) payload currently shows v0.2.118. I'll wait for it to propagate.

**Comment by jtarchie** [comment]
Yeah, still going through, watching this PR: https://github.com/Homebrew/homebrew-core/pull/181967

**Pull request merged**
