### PR TITLE
Improved fly launch / deploy for node

### PR DESCRIPTION
**Pull request by mrkurt**
* Use nixpacks if no dockerfile/buildpack
* Drop nextjs and nuxtjs templates in favor of generic node template with universal .dockerignore

### CODE REVIEW

**Review by jsierles — APPROVED** [review]
This seems reasonable.

**Comment by jsierles** [comment]
What's the verdict on this stuff? Sounded like nixpacks is producing large images?

**Comment by mrkurt** [comment]
Needs more testing, especially on Windows. Huge images are a problem, too, but might be somewhat straightforward to fix.

**Comment by dangra** [comment]
@rubys my understanding is that you are rebuilding support for node frameworks, is this PR valuable or can we close now?

**Comment by rubys** [comment]
@dangra I'm closing this.  I'm not pursuing nixpacks.  If anybody wants to resurrect this, feel free to reopen.

**Pull request closed without merging**
