### PR TITLE
Add the same validation we have in flaps so we can fail early in the deploy

### PR DESCRIPTION
**Pull request by rugwirobaker**
Companion https://github.com/superfly/nomad-firecracker/pull/1083

### CODE REVIEW

**Review by alichay — APPROVED** [review]
We should note in comments near these limits in flaps that they're replicated in flyctl, that way they don't end up out of sync

**Comment by dangra** [comment]
hey! IMO this is not the place for validations, we have a method that can validate app configuration before it reaches this point and provides better feedback to users.

 see internal/appconfig/validation.go

it should go there 🙏

**Comment by rugwirobaker** [comment]
@dangra a new validation function? Cause I kept clicking through the function and got me there.

**Comment by dangra** [comment]
+1 to reuse if there is one for checks

**Pull request merged**
