### PR TITLE
fix: Update formatting for output in checks list

### PR DESCRIPTION
**Pull request by shortdiv**
Adds better formatting for the `fly checks list --app` command

Go playground for reference: https://go.dev/play/p/ch7rYe5h7GE

Addresses #669

### CODE REVIEW

**Comment by mrkurt** [comment]
If you can think of a quick way to render the line breaks in the status output, that'd be amazing. This is good stuff that I'm guessing we'll use in machines too, at some point.

**Comment by shortdiv** [comment]
Do you mean the status like "passing" or "failed", does it need a line break?

**Comment by mrkurt** [comment]
:derp: I meant the `Output` field.

**Comment by michaeldwan** [comment]
@shortdiv nice work! There's an option [on the check output field](https://github.com/superfly/flyctl/blob/master/cmd/checks.go/#L245) that compacts the result, it's true right now. Setting that to false will _probably_ do what you want. It might look garbled if there's a bunch of leading whitespace from indention, but that's not what we're optimizing for here.

**Comment by jsierles** [comment]
Is this ready for merge?

**Comment by shortdiv** [comment]
I'd say yes

**Pull request merged**
