### PR TITLE
Obey primaryRegion on machine creation

### PR DESCRIPTION
**Pull request by dangra**
Supersedes #1149

Respect region passed at:
```
fly machine launch --region CODE
```
and in case of machine's app:
```
fly deploy --region CODE
```

### CODE REVIEW

**Comment by jsierles** [comment]
One question here is to figure out what it means to deploy with `--region`. Here it would mean 'if there are no VMs, deploy in this region'. If you already have VMs, it would mean nothing, I believe.

**Comment by dangra** [comment]
I do agree on your last statement. I didn't want to serialize primaryRegion yet because lack some of the context but IMO it should be.

The idea of respecting `--region` for `fly deploy` is only for the case when you skip deployment on `fly launch` but still want to deploy to a specific region the first time.  IMHO, we should store the primary region on the toml file.

**Comment by jsierles** [comment]
Yeah, another use case for `primary_region` will be for choosing where to run release commands by default, for things like migrations, or where to default your deploys so they match the Redis primary region.

**Comment by dangra** [comment]
looks like a strong case to store it on the toml file

**Pull request merged**
