### PR TITLE
help text for regions list

### PR DESCRIPTION
**Pull request by andie787**
### Change Summary

What and Why:

Updating the text for `regions list` help

How:

Related to:
#3104

---

### Documentation

- [ ] Fresh Produce
- [ ] In superfly/docs, or asked for help from docs team
- [x] n/a

### CODE REVIEW

**Review by dangra — COMMENTED** [review]
do we need this kind of usage distinctions now that Nomad commands are deprecated and going away?

**Comment by andie787** [comment]
I'd prefer to have only the V2 description. I'm not sure what the plan is for the `regions` command, since only `list` works for V2.

**Comment by andie787** [comment]
I would like it to go away!

New users might not know what "V1 Apps" means. :)

**Review by dangra — APPROVED** [review]
I'd ditch the "V1 usage description" in favor of always V2 but I trust your judgement.

**Comment by dangra** [comment]
Closing as v1 is gone.

**Pull request closed without merging**
