### PR TITLE
command to allocate private ipv6s to app

### PR DESCRIPTION
**Pull request by senyosimpson**
Adds the command `flyctl ips allocate-v6 --private` to allocate 6pn ips that are routable via our proxy. Also, move the IP command to the new CLI command chain.

### CODE REVIEW

**Review by shortdiv — APPROVED** [review]
Looks good to me

**Comment by senyosimpson** [comment]
Updated the output of the `fly ips list` command. It uses a table for the output, introduces a new field, `Version` for the IP version and repurposing `Type` to mean, type of address (public or private). Image below

Screenshot from 2022-07-05 09-50-01

**Comment by senyosimpson** [comment]
@jsierles updated both `fly ips list` and `fly ips private`

**Comment by jsierles** [comment]
Great! The last step here is to move it to the new command chain here https://github.com/superfly/flyctl/blob/master/internal/command/root/root.go, and to the new internal/command dir. That requires a small change to the flag parsing.

**Comment by senyosimpson** [comment]
@jsierles i think it's ready for review! Do i need to manually test the commands my side or does CI test all of them? And, I left the changes I made to `cmd/ips.go` in but I removed adding the command to `cmd/root.go`. I don't know if I should just delete `cmd/ips.go` entirely?

**Comment by jsierles** [comment]
CI does not test most commands, so you'll want to do a quick manual test. Just remove `cmd/ips`, as we don't need it anymore.

**Comment by jsierles** [comment]
I tested it, works for me!

**Pull request merged**
