### PR TITLE
feat: add debug flag

### PR DESCRIPTION
**Pull request by me-diru**
- part of #583
- added debug global flag to see debug logs of commands in terminal

Signed-off-by: Rohit Dandamudi <rohitdandamudi.1100@gmail.com>

### CODE REVIEW

**Comment by jsierles** [comment]
Thanks for the PR. Could you also look at adding this to the new commands root?

**Comment by jsierles** [comment]
Hey, are you still interested in working on this?

**Comment by me-diru** [comment]
Hey, I am not sure what you mean by new commands root, the way debug is added now.[ I think it gets added to the root here](https://github.com/superfly/flyctl/blob/master/internal/command/root/root.go#L161), not sure where the new commands root is initialised.

**Comment by jsierles** [comment]
I'll take a look again. But if you try `fly apps list --debug` you'll see that it doesn't work.

**Pull request closed without merging**
