### PR TITLE
Fix secrets import on files with \r\n as newlines

### PR DESCRIPTION
**Pull request by dangra**
I faced this issue while trying to port an app to V2 by exporting its secrets using `env` and importing with `fly secrets import <envfile`

### CODE REVIEW

**Review by alichay — APPROVED** [review]
this looks good and with a little bit of spot checking it doesn't seem to regress.

i actually got the `master` flyctl to panic with a fairly trivial testcase that had nothing to do with `\r\n`, so this will be pretty nice to have!

**Comment by alichay** [comment]
As an alternative, this could possibly use [go-envparse](https://pkg.go.dev/github.com/hashicorp/go-envparse)?

It's mentioned by T [here](https://github.com/superfly/flyctl/issues/1710#issuecomment-1429548100) as a possibility and it would also solve `export X=Y` and `X="quoted string"`

**Comment by dangra** [comment]
> As an alternative, this could possibly use [go-envparse](https://pkg.go.dev/github.com/hashicorp/go-envparse)?

go-envparse looks very good indeed, not sure if it is possible to avoid the interpolation part. Do we want that?

**Comment by dangra** [comment]
we also have the weird case of triple `"` for multiline values but should be possible to ditch them. I also wanted to add support for null terminated lines so it is easy to import files generated by `env -0`

**Comment by alichay** [comment]
> not sure if it is possible to avoid the interpolation part. Do we want that?

Probably not?

> we also have the weird case of triple `"` for multiline values but should be possible to ditch them. I also wanted to add support for null terminated lines so it is easy to import files generated by `env -0`

Yep, makes sense!

**Pull request merged**
