### PR TITLE
Fix deepsource warnings

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by matttpt** [comment]
Maybe use `//skipcq: GO-S2307` like [this](https://github.com/superfly/flyctl/commit/9ac1511dfe328bdb7f986e54097f2e2bfbcfa4d5)? Might keep the code a little cleaner.

**Comment by benwaffle** [comment]
@matttpt thanks, updated

**Review by matttpt — APPROVED** [review]
Looks good. Apparently they [addressed](https://discuss.deepsource.io/t/go-s2307-false-positives/527) `io.ReadCloser` false positives, so maybe it regressed.

**Comment by benwaffle** [comment]
Good find. I posted a comment letting them know

**Pull request merged**
