### PR TITLE
`metrics`: add opt-out, `fly metrics` command

### PR DESCRIPTION
**Pull request by alichay**
```php
flyctl on  feat/metrics/opt-out [$] via 🐹 v1.20.2 
❯ ./bin/flyctl settings analytics
Anonymized analytics: enabled

This can be controlled with fly settings analytics <enable/disable>

flyctl on  feat/metrics/opt-out [$] via 🐹 v1.20.2 
❯ ./bin/flyctl settings analytics disable
Anonymized analytics: disabled

flyctl on  feat/metrics/opt-out [$] via 🐹 v1.20.2 
❯ ./bin/flyctl settings analytics
Anonymized analytics: disabled

This can be controlled with fly settings analytics <enable/disable>

flyctl on  feat/metrics/opt-out [$] via 🐹 v1.20.2 
❯ ./bin/flyctl settings analytics enable
Anonymized analytics: enabled

flyctl on  feat/metrics/opt-out [$] via 🐹 v1.20.2 
❯ ./bin/flyctl settings analytics
Anonymized analytics: enabled

This can be controlled with fly settings analytics <enable/disable>
```

### CODE REVIEW

**Review by dangra — APPROVED** [review]
Somehow I think a top level command for an internal CLI setting is too much. I would like to group all flyctl related knobs into a single subcommand

The usual for tools like this is `config` but it is already taken, so other options are `fly options`, `fly settings`, `fly local-config` ... 

not a blocker tho.

**Comment by dangra** [comment]
btw, if we go for the top level command, brew.sh uses `brew analytics enable/disable`  which could be better name for an internal option. "metrics" already has some meaning on fly apps world.

**Comment by alichay** [comment]
great notes. I think I'm going to rework this with that in mind. ty!

**Comment by haileys** [comment]
love this!

**Pull request merged**
