### PR TITLE
Add --image to fly.toml for apps v2

### LINKED ISSUE #1820: Apps V2 - `fly launch --image` doesn't fill in `[build]` section in `fly.toml`
`flyctl v0.0.0-1677791596+dev darwin/arm64 Commit: 3c041ba5dcb5b8966fb2e8b5c62287991f648097 (master) BuildDate: 2023-03-02T21:13:16Z`

This prevents `fly deploy`.

To reproduce:

`$ ~/flyctl/bin/flyctl launch --image nginx --force-machines` 

`fly.toml` will be generated but without any `[build]` section.

Optional step: try to deploy

`$ ~/flyctl/bin/flyctl deploy --force-machines`

Get error `Error failed to fetch an image or build from source: app does not have a Dockerfile or buildpacks configured. See https://fly.io/docs/reference/configuration/#the-build-section`

### PR DESCRIPTION
**Pull request by tvdfly**
Fixes #1820

### CODE REVIEW

**Comment by tvdfly** [comment]
We'll probably want to do this for all the `[build]` config that can be specified with flags on `fly launch`. https://fly.io/docs/reference/configuration/#the-build-section

I might merge this PR as-is and make an issue for the rest of the config that's doesn't get persisted today.

**Review by dangra — COMMENTED** [review]
There is a go file only for app config setters at [internal/appconfig/setters.go](https://github.com/superfly/flyctl/blob/master/internal/appconfig/setters.go) and their corresponding tests at [setters_test.go](https://github.com/superfly/flyctl/blob/master/internal/appconfig/setters_test.go)

**Review by dangra — COMMENTED** [review]
In fact, setters are not needed as `Config.Build` is the only field that we always marshal for nomad and machines https://github.com/superfly/flyctl/blob/b7b2ce9faffd23cbb64794835589dfccdec92d24/internal/appconfig/serde.go#L109

**Comment by dangra** [comment]
#1820 was fixed by https://github.com/superfly/flyctl/pull/1830#discussion_r1128076350

**Pull request closed without merging**
