### PR TITLE
Show platform version in app listings and details

### PR DESCRIPTION
**Pull request by dangra**
```
$ fly apps list
NAME                            OWNER           STATUS  PLATFORM        LATEST DEPLOY
fly-builder-broken-water-xxx    personal        pending machines
dangra-livebook                 personal        running nomad           2022-08-02T17:35:51Z
dangra-pg-m                     personal        pending machines
dangra-pg-nomad                 personal        running nomad           2022-08-03T17:28:37Z
dangra-picoshare                personal        running nomad           2022-07-29T15:26:46Z
```

### CODE REVIEW

**Review by rugwirobaker — CHANGES_REQUESTED** [review]
Huum, for some reason Platform isn't rendering for `fly status`

**Comment by dangra** [comment]
@rugwirobaker I tried with two different apps and it shows platform correctly 🤷 

```
$ fly status -a dangra-pg-m
App
  Name     = dangra-pg-m
  Owner    = personal
  Hostname = dangra-pg-m.fly.dev
  Platform = machines

ID              STATE   REGION  IMAGE                                           CREATED                 UPDATED
1781960b5ede89  started ord     registry-1.docker.io/flyio/postgres:14.4        2022-08-03T17:30:48Z    2022-08-03T17:32:00Z
e286069f754786  started ord     registry-1.docker.io/flyio/postgres:14.4        2022-08-03T17:30:41Z    2022-08-03T17:30:45Z

$ fly status -a dangra-pg-nomad
App
  Name     = dangra-pg-nomad
  Owner    = personal
  Version  = 0
  Status   = running
  Hostname = dangra-pg-nomad.fly.dev
  Platform = nomad

Instances
ID              PROCESS VERSION REGION  DESIRED STATUS                  HEALTH CHECKS           RESTARTS        CREATED
0a264920        app     0       ord     run     running (replica)       3 total, 3 passing      0               2022-08-03T17:28:51Z
9afebe18        app     0       ord     run     running (leader)        3 total, 3 passing      0               2022-08-03T17:28:43Z

```

**Review by rugwirobaker — APPROVED** [review]

**Comment by rugwirobaker** [comment]
@dangra I was compiling on the wrong branch😅

**Comment by dangra** [comment]
no problem. thanks!

**Pull request merged**
