### PR TITLE
Experiment: add tab completion for `--app`, `--org`, and `--region`

### PR DESCRIPTION
**Pull request by alichay**
I had to do some ugly reshuffling to get this to build without circular dependencies (hello, `flagnames` package!), but the end result is _really_ slick.

https://github.com/superfly/flyctl/assets/13626644/6a188fdc-50d1-442f-8481-261c403f62eb

### CODE REVIEW

**Review by matttpt — APPROVED** [review]
Overall this looks great to me. I've enjoyed test-driving this branch locally!

I agree that the reorganization is ugly, but I likewise can't think of a better way to get around the circular dependencies—short of trying to merge the flags and preparers into one "command line processing" package, which could easily be uglier. (Though perhaps *all* the preparers could be moved into the new module at some point? Having them split might be a little confusing if you don't already know about it.)

I also wonder if it makes sense to add a (relatively short) timeout to the context for the completion functions. That way it might not freeze for too long if it can't connect or if the API is being very slow. Either way is probably fine, though, since ^C is enough to get out of it.

That's all I've got. This is really cool. Have a ✅!

**Comment by alichay** [comment]
> Though perhaps _all_ the preparers could be moved into the new module at some point?

Hilariously, this *also* causes a circular dependency. It's a nightmare!!!!!!

great idea with the cancelable context, I'll do that then merge. ty for looking this monster over!

**Comment by smorimoto** [comment]
Very nicely laid-out code and work! [I was just thinking about working on it myself](https://community.fly.io/t/auto-complete-the-app-name-on-flyctl/12933), so this is really great. But if I try this, at least it doesn't work with fish shell... Does anyone have any idea?

**Comment by alichay** [comment]
I use fish too. I will say that the way you have to configure completions is...... unintuitive haha.

Do you have a `~/.config/fish/completions/flyctl.fish`?
* If not, you'll have to run `flyctl completion fish > ~/.config/fish/completions/flyctl.fish`
* If you do, check and see if completions work for `flyctl` rather than just `fly`.
   * If they work for flyctl, you can do what I did (it's a hack), and add `alias fly=flyctl` to your `~/.config/fish/config.fish`

**Comment by smorimoto** [comment]
Oh, weirdly it seems to work with `flyctl` 🤯

**Comment by alichay** [comment]
Fair enough! Yeah, if you add the alias to your shell config it should make it work with `fly` as well.

It's a shame shell completion doesn't follow symlinks, but I guess I get why it wouldn't

**Comment by smorimoto** [comment]
Yeah, well anyway it's amazing you let me literally solve this in 10 minutes instead of spending 1 hour debugging. Thank you! 🙂

P.S. Promote this by opening a thread on the community forum! Many people may miss this, but this feature should not be missed!

**Comment by smorimoto** [comment]
OH NO. I just read this 😅 https://community.fly.io/t/quality-of-life-shell-completion-for-flyctl/13651

**Pull request merged**
