### PR TITLE
Fix FLYCTL-BE sentry error

### PR DESCRIPTION
**Pull request by dangra**
image

### CODE REVIEW

**Comment by kzys** [comment]
Personally prefer to have typed values (URL) over strings. What do you want by having strings instead?

**Comment by dangra** [comment]
@kzys I was trying to avoid returning an error as part of the method signature, a string looked much simpler but I understand the motivation to return a typed value. Will redo it a bit to avoid any error propagation still return `*url.URL`

**Comment by kzys** [comment]
If appconfig.Config doesn't have any ports, wouldn't it need to return an error still?

**Comment by dangra** [comment]
> If appconfig.Config doesn't have any ports, wouldn't it need to return an error still?

not an error but a nil value

**Comment by dangra** [comment]
> Personally prefer to have typed values (URL) over strings. What do you want by having strings instead?

please see https://github.com/superfly/flyctl/pull/2180/commits/825269d3fb79f80c738042bfef5e57fc7380ff40

**Pull request merged**
