### PR TITLE
fly launch --ha=false

### PR DESCRIPTION
**Pull request by dangra**
Support Disabling the creation of spares machines on first deploy by passing `--ha=false` flag

### CODE REVIEW

**Review by alichay — APPROVED** [review]

**Review by kzys — APPROVED** [review]

**Comment by dangra** [comment]
hey, I haven't merged this yet because I want to fix the rest of the preflight tests that were broken since introducing HA machines on first deploy.

**Comment by dangra** [comment]
FlyMachine tests too
```
l$ make preflight-test T=FlyMachine
Running Generate for Help and GraphQL client
go generate ./...
generating cli help
Running Build
go build -o bin/flyctl -ldflags="-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=2023-04-26T14:42:11Z' -X 'github.com/superfly/flyctl/internal/buildinfo.commit=8ff3a412012bc37c417190b2686c7c99b0de599f (feat/flag-ha-false)'" .
if [ -r .direnv/preflight ]; then . .direnv/preflight; fi; \
go test ./test/preflight --tags=integration -v --run=FlyMachine
=== RUN   TestFlyMachineRun_autoStartStop
--- PASS: TestFlyMachineRun_autoStartStop (27.65s)
=== RUN   TestFlyMachineRun_standbyFor
    fly_machine_test.go:97: Run a another machine and set it as standby of first
--- PASS: TestFlyMachineRun_standbyFor (22.90s)
PASS
ok      github.com/superfly/flyctl/test/preflight       50.561s
```

**Comment by dangra** [comment]
Passed AppsV2 tests  except for MigrateToV2_Volumes

```
l$ make preflight-test T=TestAppsV2
Running Generate for Help and GraphQL client
go generate ./...
generating cli help
Running Build
go build -o bin/flyctl -ldflags="-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=2023-04-26T15:49:20Z' -X 'github.com/superfly/flyctl/internal/buildinfo.commit=1fc7962b8ff585b5d6ead64183ef84ca15797cae (feat/flag-ha-false)'" .
if [ -r .direnv/preflight ]; then . .direnv/preflight; fi; \
go test ./test/preflight --tags=integration -v --run=TestAppsV2
=== RUN   TestAppsV2Example
--- PASS: TestAppsV2Example (243.36s)
=== RUN   TestAppsV2ConfigChanges
--- PASS: TestAppsV2ConfigChanges (55.54s)
=== RUN   TestAppsV2ConfigSave_ProcessGroups
--- PASS: TestAppsV2ConfigSave_ProcessGroups (41.17s)
=== RUN   TestAppsV2ConfigSave_OneMachineNoAppConfig
--- PASS: TestAppsV2ConfigSave_OneMachineNoAppConfig (12.06s)
=== RUN   TestAppsV2ConfigSave_PostgresSingleNode
--- PASS: TestAppsV2ConfigSave_PostgresSingleNode (45.82s)
=== RUN   TestAppsV2_PostgresAutostart
--- PASS: TestAppsV2_PostgresAutostart (86.62s)
=== RUN   TestAppsV2_PostgresNoMachines
--- PASS: TestAppsV2_PostgresNoMachines (38.63s)
=== RUN   TestAppsV2ConfigSave_PostgresHA
--- PASS: TestAppsV2ConfigSave_PostgresHA (90.54s)
=== RUN   TestAppsV2Config_ParseExperimental
--- PASS: TestAppsV2Config_ParseExperimental (3.70s)
=== RUN   TestAppsV2Config_ProcessGroups
--- PASS: TestAppsV2Config_ProcessGroups (96.14s)
=== RUN   TestAppsV2MigrateToV2
--- PASS: TestAppsV2MigrateToV2 (151.65s)
=== RUN   TestAppsV2MigrateToV2_Volumes
--- FAIL: TestAppsV2MigrateToV2_Volumes (150.34s)
```

**Comment by dangra** [comment]
Volume forking isn't working as expected of the fork happens before the file is synced to the filesystem.

```
$ make preflight-test T=TestAppsV2MigrateToV2_Volumes
Running Generate for Help and GraphQL client
go generate ./...
generating cli help
Running Build
go build -o bin/flyctl -ldflags="-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=2023-04-26T16:28:09Z' -X 'github.com/superfly/flyctl/internal/buildinfo.commit=2963bc93c06af9e0555a8800220063645c762071 (feat/flag-ha-false)'" .
if [ -r .direnv/preflight ]; then . .direnv/preflight; fi; \
go test ./test/preflight --tags=integration -v -timeout 30m --run=TestAppsV2MigrateToV2_Volumes
=== RUN   TestAppsV2MigrateToV2_Volumes
  1:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl orgs list --json
OUTPUT:
{
...
}

  2:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl launch --org flyctl-tests-daniel --name preflight-2023-04-3tvp3lqz --region mia --internal-port 80 --force-nomad --image nginx
OUTPUT:
Creating app in /tmp/TestAppsV2MigrateToV2_Volumes1568232401/001
Using image nginx
App will use 'mia' region as primary
Created app 'preflight-2023-04-3tvp3lqz' in organization 'flyctl-tests-daniel'
Admin URL: https://fly.io/apps/preflight-2023-04-3tvp3lqz
Hostname: preflight-2023-04-3tvp3lqz.fly.dev
Wrote config file fly.toml
Your app is ready! Deploy with `flyctl deploy`

  3:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl vol create -y --app preflight-2023-04-3tvp3lqz -s 2 --region mia vol_test
OUTPUT:
        ID: vol_0enxv307lmlv8okp
      Name: vol_test
       App: preflight-2023-04-3tvp3lqz
    Region: mia
      Zone: 6e31
   Size GB: 2
 Encrypted: true
Created at: 26 Apr 23 16:28 UTC

  4:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl deploy --now
OUTPUT:
Logs: https://fly.io/apps/preflight-2023-04-3tvp3lqz/monitoring
Visit your newly deployed app at https://preflight-2023-04-3tvp3lqz.fly.dev

  5:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl ssh console -C "bash -c 'echo myvolumehasloaded > /vol/flag.txt && sync'"
OUTPUT:

  6:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl ssh console -q -C 'cat /vol/flag.txt'
OUTPUT:
myvolumehasloaded

  7:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl migrate-to-v2 --primary-region mia --yes
OUTPUT:
INFO Using wait timeout: 2m0s lease timeout: 13s delay between lease refreshes: 4s
Updating existing machines in 'preflight-2023-04-3tvp3lqz' with rolling strategy
Wrote config file fly.toml
The following volumes have been migrated to new volumes, and are no longer needed:
 * 1 volume named 'vol_test' [replaced by 'vol_test_machines']

  8:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl status --json
OUTPUT:
{
    "AppURL": "https://2a09:8280:1::37:12c3",
    "Deployed": false,
    "Hostname": "preflight-2023-04-3tvp3lqz.fly.dev",
    "ID": "preflight-2023-04-3tvp3lqz",
    "Machines": [
        {
            "id": "148e13dc33e189",
            "name": "bold-morning-1050",
            "state": "started",
            "region": "mia",
            "image_ref": {
                "registry": "registry-1.docker.io",
                "repository": "library/nginx",
                "tag": "latest",
                "digest": "sha256:f2fee5c7194cbbfb9d2711fa5de094c797a42a51aa42b0c8ee8ca31547c872b1",
                "labels": {
                    "maintainer": "NGINX Docker Maintainers \u003cdocker-maint@nginx.com\u003e"
                }
            },
            "instance_id": "01GYZ6DMZRTKGJK4DS5Y2GYG5E",
            "private_ip": "fdaa:1:9ec5:a7b:88:cf47:78e0:2",
            "created_at": "2023-04-26T16:30:12Z",
            "updated_at": "2023-04-26T16:30:26Z",
            "config": {
                "env": {
                    "FLY_PROCESS_GROUP": "app",
                    "PRIMARY_REGION": "mia"
                },
                "init": {},
                "metadata": {
                    "fly_platform_version": "v2",
                    "fly_previous_alloc": "99df52e6-eab2-b380-5c73-765948880747",
                    "fly_process_group": "app",
                    "fly_release_id": "DD1znLMGG6J1jFwq6ejgwojAb",
                    "fly_release_version": "2"
                },
                "mounts": [
                    {
                        "encrypted": true,
                        "path": "/vol",
                        "size_gb": 2,
                        "volume": "vol_8l524yj05oe47zmp",
                        "name": "vol_test_machines"
                    }
                ],
                "services": [
                    {
                        "protocol": "tcp",
                        "internal_port": 80,
                        "ports": [
                            {
                                "port": 80,
                                "handlers": [
                                    "http"
                                ],
                                "force_https": true
                            },
                            {
                                "port": 443,
                                "handlers": [
                                    "tls",
                                    "http"
                                ]
                            }
                        ],
                        "checks": [
                            {
                                "type": "tcp",
                                "interval": "15s",
                                "timeout": "2s",
                                "grace_period": "1s"
                            }
                        ],
                        "concurrency": {
                            "type": "connections",
                            "hard_limit": 25,
                            "soft_limit": 20
                        }
                    }
                ],
                "image": "registry-1.docker.io/library/nginx:latest",
                "restart": {},
                "guest": {
                    "cpu_kind": "shared",
                    "cpus": 1,
                    "memory_mb": 256
                },
                "stop_config": {
                    "timeout": "5s",
                    "signal": "SIGINT"
                }
            },
            "events": [
                {
                    "type": "start",
                    "status": "started",
                    "source": "flyd",
                    "timestamp": 1682526626517
                },
                {
                    "type": "launch",
                    "status": "created",
                    "source": "user",
                    "timestamp": 1682526622726
                }
            ],
            "checks": [
                {
                    "name": "servicecheck-00-tcp-80",
                    "status": "passing",
                    "output": "Success",
                    "updated_at": "2023-04-26T16:30:35.86Z"
                }
            ]
        }
    ],
    "Name": "preflight-2023-04-3tvp3lqz",
    "Organization": {
        "ID": "VJeZXwpBobe7OTv1Xk80P6a5V0CxG2v3Z",
        "Name": "",
        "Slug": "flyctl-tests-daniel",
        "RawSlug": "",
        "PaidPlan": false
    },
    "PlatformVersion": "machines",
    "Status": "suspended",
    "Version": 2
}

  9:
DBGCMD: /data/src/devbox/src/flyctl/bin/flyctl ssh console -q -C 'cat /vol/flag.txt'
OUTPUT:
cat: /vol/flag.txt: No such file or directory

    result.go:42: expected successful zero exit code, got 1, for command: /data/src/devbox/src/flyctl/bin/flyctl ssh console -q -C 'cat /vol/flag.txt' [stdout]: cat: /vol/flag.txt: No such file or directory
         [strderr]: Error: ssh shell: Process exited with status 1

--- FAIL: TestAppsV2MigrateToV2_Volumes (152.42s)
FAIL
FAIL    github.com/superfly/flyctl/test/preflight       152.430s
FAIL
make: *** [Makefile:25: preflight-test] Error 1
```

**Comment by dangra** [comment]
The broken test case is something else, will merge now and look forward to fix it in another PR

**Pull request merged**
