### PR TITLE
Add an alias to `version update`: `upgrade`

### PR DESCRIPTION
**Pull request by urcadox**
Hello,

Every time I want to upgrade flyctl, I write `fly version upgrade` instead of `fly version update`. I guess I'm used to other CLI tools where `upgrade` is used for full version updates/upgrades.

Unless I'm the only one, this would be a nice addition. :D

### CODE REVIEW

**Comment by dangra** [comment]
@urcadox I tend to agree, also think it should be `fly version upgrade` first and `update` the alias for backwards compatibility, but before merging we need a few more maintainers to chime in and share their opinions. 

Please consider fixing the PR according to the linter suggestions. thanks

**Comment by alichay** [comment]
yeah I totally support this. once the linter's happy, I'd be happy to get this in there :)

**Comment by urcadox** [comment]
Great, I will fix the lint issues, and probably add another commit to transform the command into `upgrade`, with `update` as an alias.

**Comment by urcadox** [comment]
I made the updates (feel free to use or not to use the commit that renames the command and makes `update` an alias; btw I did not test this as I'm not on my usual machine right now, and I don't have an easy way to install a recent enough version of Go)

**Comment by alichay** [comment]
I made a couple tweaks, which means I ended up making a new PR from my branch. Going to go ahead and close this in favor of #2259. Thanks for getting the ball rolling and contributing, we really appreciate it!

**Pull request closed without merging**
